version: "3"
services:
  job_service:
    build: ./job_service
    container_name: job_service_container
    ports:
      - "7878:7878"
    networks:
      - employment-app
    links:
      - job_db
    restart: always
    depends_on:
      - job_db
    volumes:
      - ./job_service:/app
      - /app/node_modules
  job_db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - employment-app
    volumes:
      - job-volume:/data/db
  auth_service:
    build: ./authentication_servic
    container_name: authentication_servic_container
    ports:
      - "8080:7878"
    networks:
      - employment-app
    links:
      - auth_db
    restart: always
    depends_on:
      - auth_db
    volumes:
      - ./authentication_servic:/app
      - /app/node_modules
  auth_db:
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - employment-app
    volumes:
      - auth-volume:/data/db
  contactus_service:
    build: ./contactus_service
    container_name: contactus_service_container
    ports:
      - "5001:5001"
    networks:
      - employment-app
    links:
      - contactus_db
    restart: on-failure
    depends_on:
      - contactus_db
    volumes:
      - ./contactus_service:/app
      - /app/node_modules
  contactus_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27020:27017"
    networks:
      - employment-app
    volumes:
      - contactus-volume:/data/db
  companies_service:
    build: ./companies_service
    container_name: companies_service_container
    ports:
      - "5002:5002"
    networks:
      - employment-app
    links:
      - companies_db
    restart: on-failure
    depends_on:
      - companies_db
    volumes:
      - ./companies_service:/app
      - /app/node_modules
  companies_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27030:27017"
    networks:
      - employment-app
    volumes:
      - companies-volume:/data/db

networks:
  employment-app:
    driver: bridge
volumes:
  job-volume:
    driver: local
  auth-volume:
    driver: local
  contactus-volume:
    driver: local
  companies-volume:
    driver: local
