version: "3"
services:
  job_ratings_service:
    build: ./job_ratings_service
    container_name: job_ratings_service_container
    ports:
      - "7878:7878"
    networks:
      - employment-app
    links:
      - job_ratings_db
    restart: on-failure
    depends_on:
      - job_ratings_db
    volumes:
      - ./job_ratings_service:/app
      - /app/node_modules
  job_ratings_db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - employment-app
    volumes:
      - job_ratings-volume:/data/db
  auth_service:
    build: ./authentication_servic
    container_name: authentication_servic_container
    ports:
      - "8080:7001"
    networks:
      - employment-app
    links:
      - auth_db
    restart: on-failure
    depends_on:
      - auth_db
    volumes:
      - ./authentication_servic:/app
      - /app/node_modules
  auth_db:
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - employment-app
    volumes:
      - auth-volume:/data/db
  contactus_service:
  
    build: ./contactus_service
    container_name: contactus_service_container
    ports:
      - "5001:5001"
    networks:
      -employment-app
    links:
      - contactus_db
    restart: on-failure
    depends_on:
      - contactus_db
    volumes:
      - ./contactus_service:/app
      - /app/node_modules
  contactus_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27020:27017"
    networks:
      - employment-app
    volumes:
      - contactus-volume:/data/db
  
networks:
  employment-app:
    driver: bridge
volumes:
  job_ratings-volume:
    driver: local
  auth-volume:
    driver: local
  contactus-volume:
    driver: local
  
