version: "3"
services:

  companies_service:
    build: ./companies_service
    container_name: companies_service_container
    ports:
      - "5001:5001"
    networks:
      - employment-app
    links:
      - companies_db
    restart: on-failure
    depends_on:
      - companies_db
    volumes:
      - ./companies_service:/app
      - /app/node_modules

  companies_db:  
    image: mongo:3.6.19-xenial
    ports:
      - "27016:27015"
    networks:
      - employment-app
    volumes:
      - companies-volume:/data/db

  job_ratings_service:
    build: ./job_ratings_service
    container_name: job_ratings_service_container
    ports:
      - "7878:7878"
    networks:
      - employment-app
    links:
      - job_ratings_db
    restart: on-failure
    depends_on:
      - job_ratings_db
    volumes:
      - ./job_ratings_service:/app
      - /app/node_modules
  job_ratings_db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - employment-app
    volumes:
      - job_ratings-volume:/data/db
  auth_service:
    build: ./authentication_servic
    container_name: authentication_servic_container
    ports:
      - "8081:7001"
    networks:
      - employment-app
    links:
      - auth_db
    restart: on-failure
    depends_on:
      - auth_db
    volumes:
      - ./authentication_servic:/app
      - /app/node_modules
  auth_db:
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - employment-app
    volumes:
      - auth-volume:/data/db

networks:
  employment-app:
    driver: bridge
volumes:
  companies-volume:
    driver: local
  job_ratings-volume:
    driver: local
  auth-volume:
    driver: local
  

